// BORED
export const GET_BORED = 'GET_BORED';
export const BORED_LOADING = 'BORED_LOADING';

// QUOTES
export const GET_QUOTE = 'GET_QUOTE';
export const QUOTE_LOADING = 'QUOTE_LOADING';

// LOCAL ACTIVITIES
export const STARTINGTIME_CHANGE = 'STARTINGTIME_CHANGE';
export const ON_CHANGE_MIN = 'ON_CHANGE_MIN';
export const ON_CHANGE_HR = 'ON_CHANGE_HR';
export const CREATE_LOCALACTIVITY = 'CREATE_LOCALACTIVITY';
export const DELETE_LOCALACTIVITY = 'DELETE_LOCALACTIVITY';

// ACTIVITIES
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';

// LOGS
export const CREATE_LOG = 'CREATE_LOG';
export const DELETE_LOG = 'DELETE_LOG';

// PROJECTS
export const CREATE_PROJECT = 'CREATE_PROJECT';
